### ISSUE TITLE
provide simplified component architecture for tabs

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#172] opened 2015-07-18 16:50 UTC
Tabs are a bit tricky. We've done things this way:

https://github.com/kalamuna/kalastatic/blob/9f03333643fcdc8a9a3a32f9ea3dcf6a9ad07dfe/templates/about.html

but it requires us writing everything in HTML and is messy.
It'd be great to pull in markdown files into the tabs.

purpose of this issue is to provide a documented example of tabs

**Comment by madeofpeople** [comment] 2015-07-31 18:46
Is this a dupe of #136

**Comment by madeofpeople** [comment] 2016-03-26 00:42
Didn't josh solve this with #136? 
Shall we close this?

**Comment by andrewmallis** [comment] 2016-03-28 14:10
That was a duplicate issue. Neither has a resolution at this point. Moving to the icebox though as it isn't mission critical

**Comment by soniktrooth** [comment] 2016-03-28 16:52
I have a working example in Progenity that can be generificated and rolled in.

**Comment by andrewmallis** [comment] 2017-03-06 22:34
How do we generify and roll things in?
We no longer have a blueprint, but rather a framework.
This connects with the generator idea

**Comment by andrewmallis** [comment] 2017-03-08 20:16
Components for a given project have the potential to be an npm or composer package
How we create libraries independent of projects for re-use requires some experimentation and thinking.

**Closed** 2017-03-08 20:18 UTC
Labels: documentation, enhancement, feature
