### ISSUE TITLE
Improve commit messages the CI pushes up to it deployment target

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#263] opened 2016-01-27 21:44 UTC
In GBZ we now see the source commits + build commits, which provides more transparency on deployments.

**Comment by RobLoach** [comment] 2016-02-14 23:38
This doesn't make sense for KalaStatic, as the deployed files are completely different than the source files. On GBZ, the source is quite similar to the deployed files, so the commits can line up. Here the built files are explicitly different, by design. The GBZ deployment modal will work for Drupal-esque projects, but not for a strict prototype such as this.

We have, however, brought in the Pull Request, push remote branches change forwards. Moving this to QA, assigning back to you for exposure.

**Comment by andrewmallis** [comment] 2016-03-09 19:47
It would be useful to have the commit messages and authorship represented.

The dashboard is less meaningful than it could be, which can slow down deployments.

![kalastatic___pantheon_dashboard](https://cloud.githubusercontent.com/assets/249362/13648157/290d1f32-e5ec-11e5-899a-cf6ac9cf7c89.png)

Can we explore a different commit message and name?

**Comment by RobLoach** [comment] 2016-03-09 19:48
Possibly clean up the commit message to help clarify what is being pushed forwards:
https://www.npmjs.com/package/grunt-build-control#message

**Closed** 2017-03-06 21:31 UTC
Labels: feature
