### ISSUE TITLE
Load .json metadata from matching JSON files

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#363] opened 2016-11-23 20:55 UTC
When rendering a "mypage.twig", have it check for "mypage.json" and load that data in as metadata.

This will allow Twig templates to be included without having the YAML in there.

**Comment by RobLoach** [comment] 2016-12-13 22:16
```
mypage.twig
mypage.json
```

mypage.twig would bring in the metadata from the JSON file.

**Comment by thiagodemellobueno** [comment] 2016-12-13 22:39
duplicate of #341

**Comment by thiagodemellobueno** [comment] 2016-12-13 22:41
also would be good to be able to flag the feature on or off. 
so we don't get weirdness when the data is already in the scope/lineage.

**Closed** 2016-12-13 22:55 UTC
